### ISSUE TITLE
😕 : both payloadCreator and metaCreator try to resolve the same promise?

### ISSUE THREAD

**Issue by nightire** [acdlite/redux-actions#74]
I'm trying to write `payloadCreator` and `metaCreator` for an action, when this action been called, a promise is passed in, now both of two creators try to resolve the promise, but promise as we know, only can be resolved one time, so I'm confused: how metaCreator works exactly?

**Comment by acdlite** [comment]
> promise as we know, only can be resolved one time

Promises resolve once, but they can have multiple handlers.

```js
const foo = Promise.resolve('bar')
foo.then(bar => console.log(bar))
foo.then(bar => console.log(bar))
// Logs 'bar' twice
```

**Comment by nightire** [comment]
@acdlite I'm hoping so, but now I'm facing a problem that can't be sure what's going wrong.

Below is my payloadCreator and metaCreator:

```javascript
const payloadCreator = async response => {
  const payload = JSON.parse(await (await response).json());

  if (!payload.IsSuccess) throw new Error(payload.Message);

  return {
    // ...
  };
};

const metaCreator = async response => {
  const payload = JSON.parse(await (await response).json());

  return {
    serverError: !payload.IsSuccess,
    errorMessage: payload.Message || null,
  };
};
```

If only `payloadCreator` or `metaCreator` is passed to actionCreator, it will works as I expected. If both of them are passed in actionCreator, only `payloadCreator` will return the right results, `metaCreator` itself is still a promise which `isRejected: true`, also brings me some error messages like:

```
TypeError: Already read
    at TypeError (native)
    at _callee2$ (http://localhost:1337/assets/client.js:364:36)
    at tryCatch (http://localhost:1337/assets/vendor.js:46436:41)
    at GeneratorFunctionPrototype.invoke [as _invoke] (http://localhost:1337/assets/vendor.js:46704:23)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (http://localhost:1337/assets/vendor.js:46469:22)
    at step (http://localhost:1337/assets/client.js:281:203)
From previous event:
    at step (http://localhost:1337/assets/client.js:281:345)
    at http://localhost:1337/assets/client.js:281:391
From previous event:
    at step (http://localhost:1337/assets/client.js:281:360)
    at http://localhost:1337/assets/client.js:281:474
From previous event:
    at http://localhost:1337/assets/client.js:281:100
    at getIntroMetaCreator (http://localhost:1337/assets/client.js:383:17)
    at http://localhost:1337/assets/vendor.js:24089:34
    at Object.fetchIntro (http://localhost:1337/assets/vendor.js:22613:36)
    at Intro.componentDidMount (http://localhost:1337/assets/client.js:2276:27)
    at CallbackQueue.notifyAll (http://localhost:1337/assets/vendor.js:8288:23)
    at ReactReconcileTransaction.close (http://localhost:1337/assets/vendor.js:18042:27)
    at ReactReconcileTransaction.closeAll (http://localhost:1337/assets/vendor.js:8649:26)
    at ReactReconcileTransaction.perform (http://localhost:1337/assets/vendor.js:8596:17)
    at batchedMountComponentIntoNode (http://localhost:1337/assets/vendor.js:4496:16)
    at ReactDefaultBatchingStrategyTransaction.perform (http://localhost:1337/assets/vendor.js:8583:21)
    at Object.batchedUpdates (http://localhost:1337/assets/vendor.js:12616:20)
    at Object.batchedUpdates (http://localhost:1337/assets/vendor.js:8088:21)
    at Object._renderNewRootComponent (http://localhost:1337/assets/vendor.js:4690:19)
    at Object.wrapper [as _renderNewRootComponent] (http://localhost:1337/assets/vendor.js:3284:22)
    at Object._renderSubtreeIntoContainer (http://localhost:1337/assets/vendor.js:4764:33)
    at Object.render (http://localhost:1337/assets/vendor.js:4784:24)
    at Object.wrapper [as render] (http://localhost:1337/assets/vendor.js:3284:22)
    at render (http://localhost:1337/assets/client.js:57:23)"
```

and the related message from the server-side rendering process:

```
Unhandled rejection Error: body used already for: https://API_ENDPOINT
    at Body._decode (/Users/nightire/Code/q.cform.io/node_modules/node-fetch/lib/body.js:67:30)
    at Body.json (/Users/nightire/Code/q.cform.io/node_modules/node-fetch/lib/body.js:40:14)
    at _callee2$ (api.js:44:53)
    at tryCatch (/Users/nightire/Code/q.cform.io/node_modules/babel-regenerator-runtime/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/nightire/Code/q.cform.io/node_modules/babel-regenerator-runtime/runtime.js:329:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/nightire/Code/q.cform.io/node_modules/babel-regenerator-runtime/runtime.js:94:21)
    at step (api.js:3:1)
    at api.js:3:1
    at tryCatcher (/Users/nightire/Code/q.cform.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/nightire/Code/q.cform.io/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/nightire/Code/q.cform.io/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/nightire/Code/q.cform.io/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/nightire/Code/q.cform.io/node_modules/bluebird/js/release/promise.js:684:18)
    at Async._drainQueue (/Users/nightire/Code/q.cform.io/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/Users/nightire/Code/q.cform.io/node_modules/bluebird/js/release/async.js:136:10)
    at Async.drainQueues (/Users/nightire/Code/q.cform.io/node_modules/bluebird/js/release/async.js:16:14)
```

I noticed this error is thrown by isomorphic-fetch, but I don't understand the reason behind, can you help me on this?

**Comment by timche** [comment]
Since it's not an issue `redux-actions` itself, I'll close it for now. Can be reopened if necessary.
